# Let's start with the basics: this is a PHP project
language: php

# Disable email notifications for all builds
notifications:
  email: false

# Run on top of a few versions to check compatibility
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: SEND_COVERAGE=1 TEST_WEBSERVICES=1
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly

# Prepare environment
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then unset SEND_COVERAGE; unset TEST_WEBSERVICES; fi

# Install Composer package before testing
install:
  - composer install --no-interaction

# Run PHPUnit tests
script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover build/coverage/xml

# Send coverage to Codacy (just once per build)
after_success:
  - if [ "$SEND_COVERAGE" == "1" ]; then php vendor/bin/codacycoverage clover build/coverage/xml; fi
