<?php
namespace josemmo\Facturae\Tests;

use josemmo\Facturae\Facturae;

final class ImportTest extends AbstractTest {

  /**
   * Test import from XML for all supported schema versions.
   *
   * @param string $schemaVersion Facturae schema version
   * @param string $namespaceUri  Facturae namespace URI
   *
   * @dataProvider importSchemasProvider
   */
  public function testImportFromXml($schemaVersion, $namespaceUri) {
    $xml = $this->buildSampleXml($schemaVersion, $namespaceUri, Facturae::ISSUER_SELLER);
    $invoice = Facturae::fromXml($xml);

    $this->assertEquals($schemaVersion, $invoice->getSchemaVersion());
    $this->assertEquals(Facturae::ISSUER_SELLER, $invoice->getIssuerType());
    $this->assertEquals('A12345678', $invoice->getSeller()->taxNumber);
    $this->assertEquals('B87654321', $invoice->getBuyer()->taxNumber);
    $this->assertCount(1, $invoice->getItems());

    $json = json_decode($invoice->toJson(), true);
    $this->assertTrue(is_array($json));
    $this->assertEquals($schemaVersion, $json['header']['schemaVersion']);
    $this->assertNotEmpty($json['items'][0]['Taxes']);
    $this->assertArrayHasKey('TaxRate', $json['items'][0]['Taxes'][0]);
    $this->assertArrayHasKey('TaxBase', $json['items'][0]['Taxes'][0]);
    $this->assertArrayHasKey('TotalTaxAmount', $json['items'][0]['Taxes'][0]);
  }


  /**
   * Test import of purchase invoice (received invoice).
   *
   * In this case we validate that buyer data is preserved as "our" company
   * and that InvoiceIssuerType is imported as RE.
   */
  public function testImportPurchaseInvoiceKeepsBuyerContext() {
    $xml = $this->buildSampleXml(
      Facturae::SCHEMA_3_2_2,
      'http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml',
      Facturae::ISSUER_BUYER,
      'A99887766',
      'Nuestra Empresa S.L.',
      'B11223344',
      'Proveedor Ejemplo S.A.'
    );

    $invoice = Facturae::fromXml($xml);

    $this->assertEquals(Facturae::ISSUER_BUYER, $invoice->getIssuerType());
    $this->assertEquals('A99887766', $invoice->getBuyer()->taxNumber);
    $this->assertEquals('Nuestra Empresa S.L.', $invoice->getBuyer()->name);
    $this->assertEquals('B11223344', $invoice->getSeller()->taxNumber);
    $this->assertEquals('Proveedor Ejemplo S.A.', $invoice->getSeller()->name);

    $json = json_decode($invoice->toJson(), true);
    $this->assertEquals(Facturae::ISSUER_BUYER, $json['header']['issuerType']);
    $this->assertEquals('A99887766', $json['parties']['buyer']['taxNumber']);
    $this->assertEquals('B11223344', $json['parties']['seller']['taxNumber']);
  }


  /**
   * Test import from XML generated by this library.
   *
   * @param string $schemaVersion Facturae schema version
   *
   * @dataProvider importSchemasProvider
   */
  public function testImportRoundTripExportedXml($schemaVersion) {
    $invoice = $this->getBaseInvoice($schemaVersion);
    $invoice->addItem('Servicio de prueba', 121, 1, Facturae::TAX_IVA, 21);

    $xml = $invoice->export();
    $imported = Facturae::fromXml($xml);

    $number = $imported->getNumber();
    $this->assertEquals($schemaVersion, $imported->getSchemaVersion());
    $this->assertEquals('FAC' . date('Ym'), $number['serie']);
    $this->assertEquals('0001', $number['number']);
    $this->assertNotNull($imported->getSeller());
    $this->assertNotNull($imported->getBuyer());
    $this->assertCount(1, $imported->getItems());
  }


  /**
   * Data provider for schema versions.
   *
   * @return array
   */
  public function importSchemasProvider() {
    return [
      [Facturae::SCHEMA_3_2, 'http://www.facturae.es/Facturae/2009/v3.2/Facturae'],
      [Facturae::SCHEMA_3_2_1, 'http://www.facturae.es/Facturae/2014/v3.2.1/Facturae'],
      [Facturae::SCHEMA_3_2_2, 'http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml']
    ];
  }


  /**
   * Build a minimal Facturae XML fixture.
   *
   * @param string $schemaVersion Facturae schema version
   * @param string $namespaceUri  Facturae namespace URI
   * @param string $issuerType    Invoice issuer type
   * @param string $buyerTax      Buyer tax identification number
   * @param string $buyerName     Buyer corporate name
   * @param string $sellerTax     Seller tax identification number
   * @param string $sellerName    Seller corporate name
   * @return string               XML content
   */
  private function buildSampleXml(
    $schemaVersion,
    $namespaceUri,
    $issuerType,
    $buyerTax='B87654321',
    $buyerName='Comprador de Prueba S.L.',
    $sellerTax='A12345678',
    $sellerName='Vendedor de Prueba S.A.'
  ) {
    return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" .
      '<fe:Facturae xmlns:fe="' . $namespaceUri . '">' .
      '<FileHeader>' .
        '<SchemaVersion>' . $schemaVersion . '</SchemaVersion>' .
        '<Modality>I</Modality>' .
        '<InvoiceIssuerType>' . $issuerType . '</InvoiceIssuerType>' .
        '<Batch>' .
          '<BatchIdentifier>TEST-001</BatchIdentifier>' .
          '<InvoicesCount>1</InvoicesCount>' .
          '<TotalInvoicesAmount><TotalAmount>121.00</TotalAmount></TotalInvoicesAmount>' .
          '<TotalOutstandingAmount><TotalAmount>121.00</TotalAmount></TotalOutstandingAmount>' .
          '<TotalExecutableAmount><TotalAmount>121.00</TotalAmount></TotalExecutableAmount>' .
          '<InvoiceCurrencyCode>EUR</InvoiceCurrencyCode>' .
        '</Batch>' .
      '</FileHeader>' .
      '<Parties>' .
        '<SellerParty>' .
          '<TaxIdentification>' .
            '<PersonTypeCode>J</PersonTypeCode>' .
            '<ResidenceTypeCode>R</ResidenceTypeCode>' .
            '<TaxIdentificationNumber>' . $sellerTax . '</TaxIdentificationNumber>' .
          '</TaxIdentification>' .
          '<LegalEntity>' .
            '<CorporateName>' . $sellerName . '</CorporateName>' .
            '<AddressInSpain>' .
              '<Address>Calle Vendedor 1</Address>' .
              '<PostCode>28001</PostCode>' .
              '<Town>Madrid</Town>' .
              '<Province>Madrid</Province>' .
              '<CountryCode>ESP</CountryCode>' .
            '</AddressInSpain>' .
          '</LegalEntity>' .
        '</SellerParty>' .
        '<BuyerParty>' .
          '<TaxIdentification>' .
            '<PersonTypeCode>J</PersonTypeCode>' .
            '<ResidenceTypeCode>R</ResidenceTypeCode>' .
            '<TaxIdentificationNumber>' . $buyerTax . '</TaxIdentificationNumber>' .
          '</TaxIdentification>' .
          '<LegalEntity>' .
            '<CorporateName>' . $buyerName . '</CorporateName>' .
            '<AddressInSpain>' .
              '<Address>Calle Comprador 2</Address>' .
              '<PostCode>28002</PostCode>' .
              '<Town>Madrid</Town>' .
              '<Province>Madrid</Province>' .
              '<CountryCode>ESP</CountryCode>' .
            '</AddressInSpain>' .
          '</LegalEntity>' .
        '</BuyerParty>' .
      '</Parties>' .
      '<Invoices>' .
        '<Invoice>' .
          '<InvoiceHeader>' .
            '<InvoiceNumber>1001</InvoiceNumber>' .
            '<InvoiceSeriesCode>TEST</InvoiceSeriesCode>' .
            '<InvoiceDocumentType>FC</InvoiceDocumentType>' .
            '<InvoiceClass>OO</InvoiceClass>' .
          '</InvoiceHeader>' .
          '<InvoiceIssueData>' .
            '<IssueDate>2026-01-15</IssueDate>' .
            '<InvoiceCurrencyCode>EUR</InvoiceCurrencyCode>' .
            '<TaxCurrencyCode>EUR</TaxCurrencyCode>' .
            '<LanguageName>es</LanguageName>' .
            '<InvoiceDescription>Factura importada de prueba</InvoiceDescription>' .
          '</InvoiceIssueData>' .
          '<TaxesOutputs>' .
            '<Tax>' .
              '<TaxTypeCode>01</TaxTypeCode>' .
              '<TaxRate>21.00</TaxRate>' .
              '<TaxableBase><TotalAmount>100.00</TotalAmount></TaxableBase>' .
              '<TaxAmount><TotalAmount>21.00</TotalAmount></TaxAmount>' .
            '</Tax>' .
          '</TaxesOutputs>' .
          '<Items>' .
            '<InvoiceLine>' .
              '<ItemDescription>Servicio importado</ItemDescription>' .
              '<Quantity>1</Quantity>' .
              '<UnitOfMeasure>01</UnitOfMeasure>' .
              '<UnitPriceWithoutTax>100.00</UnitPriceWithoutTax>' .
              '<TotalCost>100.00</TotalCost>' .
              '<TaxesOutputs>' .
                '<Tax>' .
                  '<TaxTypeCode>01</TaxTypeCode>' .
                  '<TaxRate>21.00</TaxRate>' .
                  '<TaxableBase><TotalAmount>100.00</TotalAmount></TaxableBase>' .
                  '<TaxAmount><TotalAmount>21.00</TotalAmount></TaxAmount>' .
                '</Tax>' .
              '</TaxesOutputs>' .
            '</InvoiceLine>' .
          '</Items>' .
          '<InvoiceTotals>' .
            '<TotalGrossAmount>100.00</TotalGrossAmount>' .
            '<TotalGeneralDiscounts>0.00</TotalGeneralDiscounts>' .
            '<TotalGeneralSurcharges>0.00</TotalGeneralSurcharges>' .
            '<TotalGrossAmountBeforeTaxes>100.00</TotalGrossAmountBeforeTaxes>' .
            '<TotalTaxOutputs>21.00</TotalTaxOutputs>' .
            '<TotalTaxesWithheld>0.00</TotalTaxesWithheld>' .
            '<InvoiceTotal>121.00</InvoiceTotal>' .
            '<TotalOutstandingAmount>121.00</TotalOutstandingAmount>' .
            '<TotalExecutableAmount>121.00</TotalExecutableAmount>' .
          '</InvoiceTotals>' .
        '</Invoice>' .
      '</Invoices>' .
      '</fe:Facturae>';
  }
}
